name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Rodar Cypress com Action oficial
        uses: cypress-io/github-action@v6
        with:
          spec: cypress/e2e/teste
